services:
  aligner:
    container_name: tta.${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: new.Dockerfile
      args:
        - BASE_DOCKER_IMAGE=${BASE_DOCKER_IMAGE}
    image: ${COMPOSE_PROJECT_NAME}/tta
    init: true
    volumes:
      - ./:/gentle
    hostname: tta.speechpad
    working_dir: /gentle
    restart: unless-stopped
    ports:
      - "8765:8765"
    entrypoint: "/usr/local/bin/entrypoint.sh"
    command: ["python", "${APP_SCRIPT:-serve_ssh.py}"]
    logging:
      options:
        max-size: "50m"
        max-file: "4"
#    command: ["tail", "-f", "/dev/null"]